network:
  default_cidr: null
  concurrency: 64
  timeout: 1.0
  vendor_remote: true
  vendor_refresh: false
  arp_timeout: 2.0
  history_max: 100
  history_path: data/scan_history.json
notifications:
  enabled: false
  webhook_url: 
  timeout: 5.0
  discord_webhook_url: 
web:
  require_auth: false
devices:
- name: Gateway
  tags:
  - infrastructure
  ip: 192.168.1.1
- name: MacBook Pro
  tags:
  - laptop
  - personal
  mac_prefix: D4:6D:6D
